# Working with parquet files

## Objective

+ In this assignment, we will use the data downloaded with the module `data_manager` to create features.

(11 pts total)

## Prerequisites

+ This notebook assumes that price data is available to you in the environment variable `PRICE_DATA`. If you have not done so, then execute the notebook `01_materials/labs/2_data_engineering.ipynb` to create this data set.

+ Load the environment variables using dotenv. (1 pt)

In [41]:
# Write your code below.

%load_ext dotenv
%dotenv

The dotenv extension is already loaded. To reload it, use:
  %reload_ext dotenv

In [42]:
import dask.dataframe as dd

+ Load the environment variable `PRICE_DATA`.
+ Use [glob](https://docs.python.org/3/library/glob.html) to find the path of all parquet files in the directory `PRICE_DATA`.

(1pt)

In [43]:
import sys
PRICE_DATA = glob(os.path.join(os.getenv('SRC_DIR'), "data/prices_csv/stocks/*.csv"))
PRICE_DATA

['../../05_src/data/prices_csv/stocks\\A.csv',
 '../../05_src/data/prices_csv/stocks\\AA.csv',
 '../../05_src/data/prices_csv/stocks\\AACG.csv',
 '../../05_src/data/prices_csv/stocks\\AAL.csv',
 '../../05_src/data/prices_csv/stocks\\AAMC.csv',
 '../../05_src/data/prices_csv/stocks\\AAME.csv',
 '../../05_src/data/prices_csv/stocks\\AAN.csv',
 '../../05_src/data/prices_csv/stocks\\AAOI.csv',
 '../../05_src/data/prices_csv/stocks\\AAON.csv',
 '../../05_src/data/prices_csv/stocks\\AAP.csv',
 '../../05_src/data/prices_csv/stocks\\AAPL.csv',
 '../../05_src/data/prices_csv/stocks\\AAT.csv',
 '../../05_src/data/prices_csv/stocks\\AAU.csv',
 '../../05_src/data/prices_csv/stocks\\AAWW.csv',
 '../../05_src/data/prices_csv/stocks\\AAXN.csv',
 '../../05_src/data/prices_csv/stocks\\AB.csv',
 '../../05_src/data/prices_csv/stocks\\ABB.csv',
 '../../05_src/data/prices_csv/stocks\\ABBV.csv',
 '../../05_src/data/prices_csv/stocks\\ABC.csv',
 '../../05_src/data/prices_csv/stocks\\ABCB.csv',
 '../../05_src/data/prices_csv/stocks\\ABEO.csv',
 '../../05_src/data/prices_csv/stocks\\ABEV.csv',
 '../../05_src/data/prices_csv/stocks\\ABG.csv',
 '../../05_src/data/prices_csv/stocks\\ABIO.csv',
 '../../05_src/data/prices_csv/stocks\\ABM.csv',
 '../../05_src/data/prices_csv/stocks\\ABMD.csv',
 '../../05_src/data/prices_csv/stocks\\ABR.csv',
 '../../05_src/data/prices_csv/stocks\\ABT.csv',
 '../../05_src/data/prices_csv/stocks\\ABTX.csv',
 '../../05_src/data/prices_csv/stocks\\ABUS.csv',
 '../../05_src/data/prices_csv/stocks\\AC.csv',
 '../../05_src/data/prices_csv/stocks\\ACA.csv',
 '../../05_src/data/prices_csv/stocks\\ACAD.csv',
 '../../05_src/data/prices_csv/stocks\\ACAM.csv',
 '../../05_src/data/prices_csv/stocks\\ACAMU.csv',
 '../../05_src/data/prices_csv/stocks\\ACB.csv',
 '../../05_src/data/prices_csv/stocks\\ACBI.csv',
 '../../05_src/data/prices_csv/stocks\\ACC.csv',
 '../../05_src/data/prices_csv/stocks\\ACCO.csv',
 '../../05_src/data/prices_csv/stocks\\ACEL.csv',
 '../../05_src/data/prices_csv/stocks\\ACER.csv',
 '../../05_src/data/prices_csv/stocks\\ACGL.csv',
 '../../05_src/data/prices_csv/stocks\\ACGLO.csv',
 '../../05_src/data/prices_csv/stocks\\ACGLP.csv',
 '../../05_src/data/prices_csv/stocks\\ACH.csv',
 '../../05_src/data/prices_csv/stocks\\ACHC.csv',
 '../../05_src/data/prices_csv/stocks\\ACHV.csv',
 '../../05_src/data/prices_csv/stocks\\ACIA.csv',
 '../../05_src/data/prices_csv/stocks\\ACIU.csv',
 '../../05_src/data/prices_csv/stocks\\ACIW.csv',
 '../../05_src/data/prices_csv/stocks\\ACLS.csv',
 '../../05_src/data/prices_csv/stocks\\ACM.csv',
 '../../05_src/data/prices_csv/stocks\\ACMR.csv',
 '../../05_src/data/prices_csv/stocks\\ACN.csv',
 '../../05_src/data/prices_csv/stocks\\ACNB.csv',
 '../../05_src/data/prices_csv/stocks\\ACOR.csv',
 '../../05_src/data/prices_csv/stocks\\ACP.csv',
 '../../05_src/data/prices_csv/stocks\\ACRE.csv',
 '../../05_src/data/prices_csv/stocks\\ACRS.csv',
 '../../05_src/data/prices_csv/stocks\\ACRX.csv',
 '../../05_src/data/prices_csv/stocks\\ACST.csv',
 '../../05_src/data/prices_csv/stocks\\ACTG.csv',
 '../../05_src/data/prices_csv/stocks\\ACTT.csv',
 '../../05_src/data/prices_csv/stocks\\ACTTU.csv',
 '../../05_src/data/prices_csv/stocks\\ACU.csv',
 '../../05_src/data/prices_csv/stocks\\ACV.csv',
 '../../05_src/data/prices_csv/stocks\\ACY.csv',
 '../../05_src/data/prices_csv/stocks\\ADAP.csv',
 '../../05_src/data/prices_csv/stocks\\ADBE.csv',
 '../../05_src/data/prices_csv/stocks\\ADC.csv',
 '../../05_src/data/prices_csv/stocks\\ADES.csv',
 '../../05_src/data/prices_csv/stocks\\ADI.csv',
 '../../05_src/data/prices_csv/stocks\\ADIL.csv',
 '../../05_src/data/prices_csv/stocks\\ADM.csv',
 '../../05_src/data/prices_csv/stocks\\ADMA.csv',
 '../../05_src/data/prices_csv/stocks\\ADMP.csv',
 '../../05_src/data/prices_csv/stocks\\ADMS.csv',
 '../../05_src/data/prices_csv/stocks\\ADNT.csv',
 '../../05_src/data/prices_csv/stocks\\ADP.csv',
 '../../05_src/data/prices_csv/stocks\\ADPT.csv',
 '../../05_src/data/prices_csv/stocks\\ADRO.csv',
 '../../05_src/data/prices_csv/stocks\\ADS.csv',
 '../../05_src/data/prices_csv/stocks\\ADSK.csv',
 '../../05_src/data/prices_csv/stocks\\ADSW.csv',
 '../../05_src/data/prices_csv/stocks\\ADT.csv',
 '../../05_src/data/prices_csv/stocks\\ADTN.csv',
 '../../05_src/data/prices_csv/stocks\\ADUS.csv',
 '../../05_src/data/prices_csv/stocks\\ADVM.csv',
 '../../05_src/data/prices_csv/stocks\\ADX.csv',
 '../../05_src/data/prices_csv/stocks\\ADXN.csv',
 '../../05_src/data/prices_csv/stocks\\ADXS.csv',
 '../../05_src/data/prices_csv/stocks\\AE.csv',
 '../../05_src/data/prices_csv/stocks\\AEB.csv',
 '../../05_src/data/prices_csv/stocks\\AEE.csv',
 '../../05_src/data/prices_csv/stocks\\AEF.csv',
 '../../05_src/data/prices_csv/stocks\\AEFC.csv',
 '../../05_src/data/prices_csv/stocks\\AEG.csv',
 '../../05_src/data/prices_csv/stocks\\AEGN.csv',
 '../../05_src/data/prices_csv/stocks\\AEHR.csv',
 '../../05_src/data/prices_csv/stocks\\AEIS.csv',
 '../../05_src/data/prices_csv/stocks\\AEL.csv',
 '../../05_src/data/prices_csv/stocks\\AEM.csv',
 '../../05_src/data/prices_csv/stocks\\AEMD.csv',
 '../../05_src/data/prices_csv/stocks\\AEO.csv',
 '../../05_src/data/prices_csv/stocks\\AEP.csv',
 '../../05_src/data/prices_csv/stocks\\AER.csv',
 '../../05_src/data/prices_csv/stocks\\AERI.csv',
 '../../05_src/data/prices_csv/stocks\\AES.csv',
 '../../05_src/data/prices_csv/stocks\\AESE.csv',
 '../../05_src/data/prices_csv/stocks\\AEY.csv',
 '../../05_src/data/prices_csv/stocks\\AEYE.csv',
 '../../05_src/data/prices_csv/stocks\\AEZS.csv',
 '../../05_src/data/prices_csv/stocks\\AFB.csv',
 '../../05_src/data/prices_csv/stocks\\AFC.csv',
 '../../05_src/data/prices_csv/stocks\\AFG.csv',
 '../../05_src/data/prices_csv/stocks\\AFGC.csv',
 '../../05_src/data/prices_csv/stocks\\AFGH.csv',
 '../../05_src/data/prices_csv/stocks\\AFH.csv',
 '../../05_src/data/prices_csv/stocks\\AFI.csv',
 '../../05_src/data/prices_csv/stocks\\AFIN.csv',
 '../../05_src/data/prices_csv/stocks\\AFINP.csv',
 '../../05_src/data/prices_csv/stocks\\AFL.csv',
 '../../05_src/data/prices_csv/stocks\\AFMD.csv',
 '../../05_src/data/prices_csv/stocks\\AFT.csv',
 '../../05_src/data/prices_csv/stocks\\AFYA.csv',
 '../../05_src/data/prices_csv/stocks\\AG.csv',
 '../../05_src/data/prices_csv/stocks\\AGBA.csv',
 '../../05_src/data/prices_csv/stocks\\AGBAU.csv',
 '../../05_src/data/prices_csv/stocks\\AGCO.csv',
 '../../05_src/data/prices_csv/stocks\\AGD.csv',
 '../../05_src/data/prices_csv/stocks\\AGE.csv',
 '../../05_src/data/prices_csv/stocks\\AGEN.csv',
 '../../05_src/data/prices_csv/stocks\\AGFS.csv',
 '../../05_src/data/prices_csv/stocks\\AGI.csv',
 '../../05_src/data/prices_csv/stocks\\AGIO.csv',
 '../../05_src/data/prices_csv/stocks\\AGLE.csv',
 '../../05_src/data/prices_csv/stocks\\AGM-A.csv',
 '../../05_src/data/prices_csv/stocks\\AGM.csv',
 '../../05_src/data/prices_csv/stocks\\AGMH.csv',
 '../../05_src/data/prices_csv/stocks\\AGN.csv',
 '../../05_src/data/prices_csv/stocks\\AGNC.csv',
 '../../05_src/data/prices_csv/stocks\\AGNCM.csv',
 '../../05_src/data/prices_csv/stocks\\AGNCN.csv',
 '../../05_src/data/prices_csv/stocks\\AGNCO.csv',
 '../../05_src/data/prices_csv/stocks\\AGNCP.csv',
 '../../05_src/data/prices_csv/stocks\\AGO.csv',
 '../../05_src/data/prices_csv/stocks\\AGR.csv',
 '../../05_src/data/prices_csv/stocks\\AGRO.csv',
 '../../05_src/data/prices_csv/stocks\\AGRX.csv',
 '../../05_src/data/prices_csv/stocks\\AGS.csv',
 '../../05_src/data/prices_csv/stocks\\AGTC.csv',
 '../../05_src/data/prices_csv/stocks\\AGX.csv',
 '../../05_src/data/prices_csv/stocks\\AGYS.csv',
 '../../05_src/data/prices_csv/stocks\\AHC.csv',
 '../../05_src/data/prices_csv/stocks\\AHCO.csv',
 '../../05_src/data/prices_csv/stocks\\AHH.csv',
 '../../05_src/data/prices_csv/stocks\\AHPI.csv',
 '../../05_src/data/prices_csv/stocks\\AHT.csv',
 '../../05_src/data/prices_csv/stocks\\AI.csv',
 '../../05_src/data/prices_csv/stocks\\AIC.csv',
 '../../05_src/data/prices_csv/stocks\\AIF.csv',
 '../../05_src/data/prices_csv/stocks\\AIG.csv',
 '../../05_src/data/prices_csv/stocks\\AIH.csv',
 '../../05_src/data/prices_csv/stocks\\AIHS.csv',
 '../../05_src/data/prices_csv/stocks\\AIKI.csv',
 '../../05_src/data/prices_csv/stocks\\AIM.csv',
 '../../05_src/data/prices_csv/stocks\\AIMC.csv',
 '../../05_src/data/prices_csv/stocks\\AIMT.csv',
 '../../05_src/data/prices_csv/stocks\\AIN.csv',
 '../../05_src/data/prices_csv/stocks\\AINC.csv',
 '../../05_src/data/prices_csv/stocks\\AINV.csv',
 '../../05_src/data/prices_csv/stocks\\AIO.csv',
 '../../05_src/data/prices_csv/stocks\\AIR.csv',
 '../../05_src/data/prices_csv/stocks\\AIRG.csv',
 '../../05_src/data/prices_csv/stocks\\AIRI.csv',
 '../../05_src/data/prices_csv/stocks\\AIRT.csv',
 '../../05_src/data/prices_csv/stocks\\AIRTP.csv',
 '../../05_src/data/prices_csv/stocks\\AIT.csv',
 '../../05_src/data/prices_csv/stocks\\AIV.csv',
 '../../05_src/data/prices_csv/stocks\\AIW.csv',
 '../../05_src/data/prices_csv/stocks\\AIZ.csv',
 '../../05_src/data/prices_csv/stocks\\AIZP.csv',
 '../../05_src/data/prices_csv/stocks\\AJG.csv',
 '../../05_src/data/prices_csv/stocks\\AJRD.csv',
 '../../05_src/data/prices_csv/stocks\\AJX.csv',
 '../../05_src/data/prices_csv/stocks\\AJXA.csv',
 '../../05_src/data/prices_csv/stocks\\AKAM.csv',
 '../../05_src/data/prices_csv/stocks\\AKBA.csv',
 '../../05_src/data/prices_csv/stocks\\AKCA.csv',
 '../../05_src/data/prices_csv/stocks\\AKER.csv',
 '../../05_src/data/prices_csv/stocks\\AKG.csv',
 '../../05_src/data/prices_csv/stocks\\AKR.csv',
 '../../05_src/data/prices_csv/stocks\\AKRO.csv',
 '../../05_src/data/prices_csv/stocks\\AKRX.csv',
 '../../05_src/data/prices_csv/stocks\\AKTS.csv',
 '../../05_src/data/prices_csv/stocks\\AKTX.csv',
 '../../05_src/data/prices_csv/stocks\\AL.csv',
 '../../05_src/data/prices_csv/stocks\\ALAC.csv',
 '../../05_src/data/prices_csv/stocks\\ALACR.csv',
 '../../05_src/data/prices_csv/stocks\\ALACU.csv',
 '../../05_src/data/prices_csv/stocks\\ALB.csv',
 '../../05_src/data/prices_csv/stocks\\ALBO.csv',
 '../../05_src/data/prices_csv/stocks\\ALC.csv',
 '../../05_src/data/prices_csv/stocks\\ALCO.csv',
 '../../05_src/data/prices_csv/stocks\\ALDX.csv',
 '../../05_src/data/prices_csv/stocks\\ALE.csv',
 '../../05_src/data/prices_csv/stocks\\ALEC.csv',
 '../../05_src/data/prices_csv/stocks\\ALEX.csv',
 '../../05_src/data/prices_csv/stocks\\ALG.csv',
 '../../05_src/data/prices_csv/stocks\\ALGN.csv',
 '../../05_src/data/prices_csv/stocks\\ALGR.csv',
 '../../05_src/data/prices_csv/stocks\\ALGRU.csv',
 '../../05_src/data/prices_csv/stocks\\ALGT.csv',
 '../../05_src/data/prices_csv/stocks\\ALIM.csv',
 '../../05_src/data/prices_csv/stocks\\ALJJ.csv',
 '../../05_src/data/prices_csv/stocks\\ALK.csv',
 '../../05_src/data/prices_csv/stocks\\ALKS.csv',
 '../../05_src/data/prices_csv/stocks\\ALL.csv',
 '../../05_src/data/prices_csv/stocks\\ALLE.csv',
 '../../05_src/data/prices_csv/stocks\\ALLK.csv',
 '../../05_src/data/prices_csv/stocks\\ALLO.csv',
 '../../05_src/data/prices_csv/stocks\\ALLT.csv',
 '../../05_src/data/prices_csv/stocks\\ALLY.csv',
 '../../05_src/data/prices_csv/stocks\\ALNA.csv',
 '../../05_src/data/prices_csv/stocks\\ALNY.csv',
 '../../05_src/data/prices_csv/stocks\\ALO.csv',
 '../../05_src/data/prices_csv/stocks\\ALOT.csv',
 '../../05_src/data/prices_csv/stocks\\ALPN.csv',
 '../../05_src/data/prices_csv/stocks\\ALRM.csv',
 '../../05_src/data/prices_csv/stocks\\ALRN.csv',
 '../../05_src/data/prices_csv/stocks\\ALRS.csv',
 '../../05_src/data/prices_csv/stocks\\ALSK.csv',
 '../../05_src/data/prices_csv/stocks\\ALSN.csv',
 '../../05_src/data/prices_csv/stocks\\ALT.csv',
 '../../05_src/data/prices_csv/stocks\\ALTG.csv',
 '../../05_src/data/prices_csv/stocks\\ALTM.csv',
 '../../05_src/data/prices_csv/stocks\\ALTR.csv',
 '../../05_src/data/prices_csv/stocks\\ALUS.csv',
 '../../05_src/data/prices_csv/stocks\\ALV.csv',
 '../../05_src/data/prices_csv/stocks\\ALX.csv',
 '../../05_src/data/prices_csv/stocks\\ALXN.csv',
 '../../05_src/data/prices_csv/stocks\\ALYA.csv',
 '../../05_src/data/prices_csv/stocks\\AM.csv',
 '../../05_src/data/prices_csv/stocks\\AMAG.csv',
 '../../05_src/data/prices_csv/stocks\\AMAL.csv',
 '../../05_src/data/prices_csv/stocks\\AMAT.csv',
 '../../05_src/data/prices_csv/stocks\\AMBA.csv',
 '../../05_src/data/prices_csv/stocks\\AMBC.csv',
 '../../05_src/data/prices_csv/stocks\\AMBO.csv',
 '../../05_src/data/prices_csv/stocks\\AMC.csv',
 '../../05_src/data/prices_csv/stocks\\AMCI.csv',
 '../../05_src/data/prices_csv/stocks\\AMCIU.csv',
 '../../05_src/data/prices_csv/stocks\\AMCR.csv',
 '../../05_src/data/prices_csv/stocks\\AMCX.csv',
 '../../05_src/data/prices_csv/stocks\\AMD.csv',
 '../../05_src/data/prices_csv/stocks\\AME.csv',
 '../../05_src/data/prices_csv/stocks\\AMED.csv',
 '../../05_src/data/prices_csv/stocks\\AMEH.csv',
 '../../05_src/data/prices_csv/stocks\\AMG.csv',
 '../../05_src/data/prices_csv/stocks\\AMGN.csv',
 '../../05_src/data/prices_csv/stocks\\AMH.csv',
 '../../05_src/data/prices_csv/stocks\\AMHC.csv',
 '../../05_src/data/prices_csv/stocks\\AMHCU.csv',
 '../../05_src/data/prices_csv/stocks\\AMJ.csv',
 '../../05_src/data/prices_csv/stocks\\AMK.csv',
 '../../05_src/data/prices_csv/stocks\\AMKR.csv',
 '../../05_src/data/prices_csv/stocks\\AMN.csv',
 '../../05_src/data/prices_csv/stocks\\AMNB.csv',
 '../../05_src/data/prices_csv/stocks\\AMOT.csv',
 '../../05_src/data/prices_csv/stocks\\AMOV.csv',
 '../../05_src/data/prices_csv/stocks\\AMP.csv',
 '../../05_src/data/prices_csv/stocks\\AMPE.csv',
 '../../05_src/data/prices_csv/stocks\\AMPH.csv',
 '../../05_src/data/prices_csv/stocks\\AMPY.csv',
 '../../05_src/data/prices_csv/stocks\\AMRB.csv',
 '../../05_src/data/prices_csv/stocks\\AMRC.csv',
 '../../05_src/data/prices_csv/stocks\\AMRH.csv',
 '../../05_src/data/prices_csv/stocks\\AMRK.csv',
 '../../05_src/data/prices_csv/stocks\\AMRN.csv',
 '../../05_src/data/prices_csv/stocks\\AMRS.csv',
 '../../05_src/data/prices_csv/stocks\\AMRX.csv',
 '../../05_src/data/prices_csv/stocks\\AMS.csv',
 '../../05_src/data/prices_csv/stocks\\AMSC.csv',
 '../../05_src/data/prices_csv/stocks\\AMSF.csv',
 '../../05_src/data/prices_csv/stocks\\AMSWA.csv',
 '../../05_src/data/prices_csv/stocks\\AMT.csv',
 '../../05_src/data/prices_csv/stocks\\AMTB.csv',
 '../../05_src/data/prices_csv/stocks\\AMTBB.csv',
 '../../05_src/data/prices_csv/stocks\\AMTD.csv',
 '../../05_src/data/prices_csv/stocks\\AMTX.csv',
 '../../05_src/data/prices_csv/stocks\\AMU.csv',
 '../../05_src/data/prices_csv/stocks\\AMUB.csv',
 '../../05_src/data/prices_csv/stocks\\AMWD.csv',
 '../../05_src/data/prices_csv/stocks\\AMX.csv',
 '../../05_src/data/prices_csv/stocks\\AMZN.csv',
 '../../05_src/data/prices_csv/stocks\\AN.csv',
 '../../05_src/data/prices_csv/stocks\\ANAB.csv',
 '../../05_src/data/prices_csv/stocks\\ANAT.csv',
 '../../05_src/data/prices_csv/stocks\\ANCN.csv',
 '../../05_src/data/prices_csv/stocks\\ANDA.csv',
 '../../05_src/data/prices_csv/stocks\\ANDAU.csv',
 '../../05_src/data/prices_csv/stocks\\ANDE.csv',
 '../../05_src/data/prices_csv/stocks\\ANET.csv',
 '../../05_src/data/prices_csv/stocks\\ANF.csv',
 '../../05_src/data/prices_csv/stocks\\ANGI.csv',
 '../../05_src/data/prices_csv/stocks\\ANGO.csv',
 '../../05_src/data/prices_csv/stocks\\ANH.csv',
 '../../05_src/data/prices_csv/stocks\\ANIK.csv',
 '../../05_src/data/prices_csv/stocks\\ANIP.csv',
 '../../05_src/data/prices_csv/stocks\\ANIX.csv',
 '../../05_src/data/prices_csv/stocks\\ANPC.csv',
 '../../05_src/data/prices_csv/stocks\\ANSS.csv',
 '../../05_src/data/prices_csv/stocks\\ANTE.csv',
 '../../05_src/data/prices_csv/stocks\\ANTM.csv',
 '../../05_src/data/prices_csv/stocks\\ANVS.csv',
 '../../05_src/data/prices_csv/stocks\\ANY.csv',
 '../../05_src/data/prices_csv/stocks\\AOBC.csv',
 '../../05_src/data/prices_csv/stocks\\AOD.csv',
 '../../05_src/data/prices_csv/stocks\\AON.csv',
 '../../05_src/data/prices_csv/stocks\\AOS.csv',
 '../../05_src/data/prices_csv/stocks\\AOSL.csv',
 '../../05_src/data/prices_csv/stocks\\AP.csv',
 '../../05_src/data/prices_csv/stocks\\APA.csv',
 '../../05_src/data/prices_csv/stocks\\APAM.csv',
 '../../05_src/data/prices_csv/stocks\\APD.csv',
 '../../05_src/data/prices_csv/stocks\\APDN.csv',
 '../../05_src/data/prices_csv/stocks\\APEI.csv',
 '../../05_src/data/prices_csv/stocks\\APEN.csv',
 '../../05_src/data/prices_csv/stocks\\APEX.csv',
 '../../05_src/data/prices_csv/stocks\\APH.csv',
 '../../05_src/data/prices_csv/stocks\\APHA.csv',
 '../../05_src/data/prices_csv/stocks\\APLE.csv',
 '../../05_src/data/prices_csv/stocks\\APLS.csv',
 '../../05_src/data/prices_csv/stocks\\APLT.csv',
 '../../05_src/data/prices_csv/stocks\\APM.csv',
 '../../05_src/data/prices_csv/stocks\\APO.csv',
 '../../05_src/data/prices_csv/stocks\\APOG.csv',
 '../../05_src/data/prices_csv/stocks\\APOP.csv',
 '../../05_src/data/prices_csv/stocks\\APPF.csv',
 '../../05_src/data/prices_csv/stocks\\APPN.csv',
 '../../05_src/data/prices_csv/stocks\\APPS.csv',
 '../../05_src/data/prices_csv/stocks\\APRE.csv',
 '../../05_src/data/prices_csv/stocks\\APRN.csv',
 '../../05_src/data/prices_csv/stocks\\APT.csv',
 '../../05_src/data/prices_csv/stocks\\APTO.csv',
 '../../05_src/data/prices_csv/stocks\\APTS.csv',
 '../../05_src/data/prices_csv/stocks\\APTV.csv',
 '../../05_src/data/prices_csv/stocks\\APTX.csv',
 '../../05_src/data/prices_csv/stocks\\APVO.csv',
 '../../05_src/data/prices_csv/stocks\\APWC.csv',
 '../../05_src/data/prices_csv/stocks\\APXT.csv',
 '../../05_src/data/prices_csv/stocks\\APXTU.csv',
 '../../05_src/data/prices_csv/stocks\\APY.csv',
 '../../05_src/data/prices_csv/stocks\\APYX.csv',
 '../../05_src/data/prices_csv/stocks\\AQB.csv',
 '../../05_src/data/prices_csv/stocks\\AQMS.csv',
 '../../05_src/data/prices_csv/stocks\\AQN.csv',
 '../../05_src/data/prices_csv/stocks\\AQNA.csv',
 '../../05_src/data/prices_csv/stocks\\AQNB.csv',
 '../../05_src/data/prices_csv/stocks\\AQST.csv',
 '../../05_src/data/prices_csv/stocks\\AQUA.csv',
 '../../05_src/data/prices_csv/stocks\\AR.csv',
 '../../05_src/data/prices_csv/stocks\\ARA.csv',
 '../../05_src/data/prices_csv/stocks\\ARAV.csv',
 '../../05_src/data/prices_csv/stocks\\ARAY.csv',
 '../../05_src/data/prices_csv/stocks\\ARC.csv',
 '../../05_src/data/prices_csv/stocks\\ARCB.csv',
 '../../05_src/data/prices_csv/stocks\\ARCC.csv',
 '../../05_src/data/prices_csv/stocks\\ARCE.csv',
 '../../05_src/data/prices_csv/stocks\\ARCH.csv',
 '../../05_src/data/prices_csv/stocks\\ARCO.csv',
 '../../05_src/data/prices_csv/stocks\\ARCT.csv',
 '../../05_src/data/prices_csv/stocks\\ARD.csv',
 '../../05_src/data/prices_csv/stocks\\ARDC.csv',
 '../../05_src/data/prices_csv/stocks\\ARDS.csv',
 '../../05_src/data/prices_csv/stocks\\ARDX.csv',
 '../../05_src/data/prices_csv/stocks\\ARE.csv',
 '../../05_src/data/prices_csv/stocks\\AREC.csv',
 '../../05_src/data/prices_csv/stocks\\ARES.csv',
 '../../05_src/data/prices_csv/stocks\\ARGD.csv',
 '../../05_src/data/prices_csv/stocks\\ARGO.csv',
 '../../05_src/data/prices_csv/stocks\\ARGX.csv',
 '../../05_src/data/prices_csv/stocks\\ARI.csv',
 '../../05_src/data/prices_csv/stocks\\ARKR.csv',
 '../../05_src/data/prices_csv/stocks\\ARL.csv',
 '../../05_src/data/prices_csv/stocks\\ARLO.csv',
 '../../05_src/data/prices_csv/stocks\\ARLP.csv',
 '../../05_src/data/prices_csv/stocks\\ARMK.csv',
 '../../05_src/data/prices_csv/stocks\\ARMP.csv',
 '../../05_src/data/prices_csv/stocks\\ARNA.csv',
 '../../05_src/data/prices_csv/stocks\\ARNC.csv',
 '../../05_src/data/prices_csv/stocks\\AROC.csv',
 '../../05_src/data/prices_csv/stocks\\AROW.csv',
 '../../05_src/data/prices_csv/stocks\\ARPO.csv',
 '../../05_src/data/prices_csv/stocks\\ARQT.csv',
 '../../05_src/data/prices_csv/stocks\\ARR.csv',
 '../../05_src/data/prices_csv/stocks\\ARTL.csv',
 '../../05_src/data/prices_csv/stocks\\ARTNA.csv',
 '../../05_src/data/prices_csv/stocks\\ARTW.csv',
 '../../05_src/data/prices_csv/stocks\\ARVN.csv',
 '../../05_src/data/prices_csv/stocks\\ARW.csv',
 '../../05_src/data/prices_csv/stocks\\ARWR.csv',

In [44]:
import os
from glob import glob

# Write your code below.

import sys
PRICE_DATA = glob(os.path.join(os.getenv('SRC_DIR'), "data/prices_csv/stocks/*.csv"))
PRICE_DATA = os.getenv("PRICE_DATA")
parquet_files = glob(os.path.join(PRICE_DATA, "**/*.parquet"), recursive = True)
df = dd.read_parquet(parquet_files)

For each ticker and using Dask, do the following:

+ Add lags for variables Close and Adj_Close.
+ Add returns based on Close:
    
    - `returns`: (Close / Close_lag_1) - 1

+ Add the following range: 

    - `hi_lo_range`: this is the day's High minus Low.

+ Assign the result to `dd_feat`.

(4 pt)

In [45]:
# Write your code below.

import dask.dataframe as dd

#read all parquet files
dd_px = dd.read_parquet(parquet_files).set_index("ticker")

#adding lag for variables Close and Adj_Close
dd_shift = dd_px.groupby('ticker', group_keys=False).apply(
    lambda x: x.assign(Close_lag_1 = x['Close'].shift(1)))

#adding returns based on Close price
dd_returns = dd_shift.assign(
    Returns = lambda x: x['Close']/x['Close_lag_1'] - 1
)

#adding hi_lo_range
dd_hi_lo = dd_returns.assign(
    Hi_Lo_Range = lambda x: x['High'] - x['Low']
)

#assigning to dd_feat
dd_feat = dd_hi_lo
dd_feat.head()

C:\Users\Localadmin\AppData\Local\Temp\ipykernel_10244\2971178016.py:9: UserWarning: `meta` is not specified, inferred from partial data.
Please provide `meta` if the result is unexpected.
  Before: .apply(func)
  After:  .apply(func, meta={'x': 'f8', 'y': 'f8'}) for dataframe result
  or:     .apply(func, meta=('x', 'f8'))            for series result

  dd_shift = dd_px.groupby('ticker', group_keys=False).apply(

,Date,Open,High,Low,Close,Adj Close,Volume,source,Year,Close_lag_1,Returns,Hi_Lo_Range
ticker,,,,,,,,,,,,
AAN,2015-01-02,30.809999,30.860001,30.040001,30.620001,30.087009,898900,AAN.csv,2015,NaN,NaN,0.820000
AAN,2015-01-05,30.350000,30.690001,30.230000,30.500000,29.969103,503900,AAN.csv,2015,30.620001,-0.003919,0.460001
AAN,2015-01-06,30.530001,30.540001,29.090000,29.360001,28.848948,1222500,AAN.csv,2015,30.500000,-0.037377,1.450001
AAN,2015-01-07,29.590000,30.350000,29.400000,30.250000,29.723450,917300,AAN.csv,2015,29.360001,0.030313,0.950001
AAN,2015-01-08,30.700001,30.840000,30.420000,30.740000,30.204924,1345300,AAN.csv,2015,30.250000,0.016198,0.420000

+ Convert the Dask data frame to a pandas data frame. 
+ Add a new feature containing the moving average of `returns` using a window of 10 days. There are several ways to solve this task, a simple one uses `.rolling(10).mean()`.

(3 pt)

In [46]:
# Write your code below.

# Converting Dask DataFrame to Pandas DataFrame
df_feat = dd_feat.compute()

# Calculating 10-day moving average of returns
df_feat["returns_ma10"] = df_feat.groupby("ticker")["Returns"].transform(lambda x: x.rolling(10).mean())

df_feat.head(15)

,Date,Open,High,Low,Close,Adj Close,Volume,source,Year,Close_lag_1,Returns,Hi_Lo_Range,returns_ma10
ticker,,,,,,,,,,,,,
AAN,1982-11-04,0.0,1.024691,1.012346,1.012346,-1.263439e+21,9182700,AAN.csv,1982,NaN,NaN,0.012346,NaN
AAN,1982-11-05,0.0,1.049383,1.024691,1.024691,-1.278846e+21,2370600,AAN.csv,1982,1.012346,0.012195,0.024691,NaN
AAN,1982-11-08,0.0,1.061728,1.037037,1.037037,-1.294253e+21,1174500,AAN.csv,1982,1.024691,0.012048,0.024691,NaN
AAN,1982-11-09,0.0,1.061728,1.037037,1.037037,-1.294253e+21,1344600,AAN.csv,1982,1.037037,0.000000,0.024691,NaN
AAN,1982-11-10,0.0,1.098765,1.074074,1.074074,-1.340476e+21,819400,AAN.csv,1982,1.037037,0.035714,0.024691,NaN
AAN,1982-11-11,0.0,1.086420,1.061728,1.061728,-1.325069e+21,475200,AAN.csv,1982,1.074074,-0.011494,0.024691,NaN
AAN,1982-11-12,0.0,1.111111,1.086420,1.086420,-1.355885e+21,479200,AAN.csv,1982,1.061728,0.023256,0.024691,NaN
AAN,1982-11-15,0.0,1.086420,1.061728,1.061728,-1.325069e+21,195700,AAN.csv,1982,1.086420,-0.022727,0.024691,NaN
AAN,1982-11-16,0.0,1.061728,1.037037,1.037037,-1.294253e+21,1034100,AAN.csv,1982,1.061728,-0.023256,0.024691,NaN
AAN,1982-11-17,0.0,1.049383,1.024691,1.024691,-1.278846e+21,1232500,AAN.csv,1982,1.037037,-0.011905,0.024691,NaN
AAN,1982-11-18,0.0,1.061728,1.037037,1.037037,-1.294253e+21,357700,AAN.csv,1982,1.024691,0.012048,0.024691,0.002588
AAN,1982-11-19,0.0,1.061728,1.049383,1.049383,-1.309661e+21,459000,AAN.csv,1982,1.037037,0.011905,0.012346,0.002559
AAN,1982-11-22,0.0,1.012346,0.975309,0.975309,-1.217214e+21,352300,AAN.csv,1982,1.049383,-0.070588,0.037037,-0.005705
AAN,1982-11-23,0.0,1.000000,0.975309,0.975309,-1.217214e+21,268600,AAN.csv,1982,0.975309,0.000000,0.024691,-0.005705
AAN,1982-11-24,0.0,0.987654,0.975309,0.975309,-1.217214e+21,207900,AAN.csv,1982,0.975309,0.000000,0.012346,-0.009276

Please comment:

+ Was it necessary to convert to pandas to calculate the moving average return?
+ Would it have been better to do it in Dask? Why?

(1 pt)


+ **Was it necessary to convert to pandas to calculate the moving average return?**  
No, it wasn't necessary. Dask also supports rolling operations however, rolling operations in Dask can be slower especially if the dataset is small enough to fit into memory.

+ **Would it have been better to do it in Dask? Why?**  
It would have been better to do it in Dask if the data was large and it wouldn't fit into memory. Dask would have distributed the computation and make it scalable.

## Criteria

The [rubric](./assignment_1_rubric_clean.xlsx) contains the criteria for grading.

## Submission Information

🚨 **Please review our [Assignment Submission Guide](https://github.com/UofT-DSI/onboarding/blob/main/onboarding_documents/submissions.md)** 🚨 for detailed instructions on how to format, branch, and submit your work. Following these guidelines is crucial for your submissions to be evaluated correctly.

### Submission Parameters:
* Submission Due Date: `HH:MM AM/PM - DD/MM/YYYY`
* The branch name for your repo should be: `assignment-1`
* What to submit for this assignment:
    * This Jupyter Notebook (assignment_1.ipynb) should be populated and should be the only change in your pull request.
* What the pull request link should look like for this assignment: `https://github.com/<your_github_username>/production/pull/<pr_id>`
    * Open a private window in your browser. Copy and paste the link to your pull request into the address bar. Make sure you can see your pull request properly. This helps the technical facilitator and learning support staff review your submission easily.

Checklist:
- [ ] Created a branch with the correct naming convention.
- [ ] Ensured that the repository is public.
- [ ] Reviewed the PR description guidelines and adhered to them.
- [ ] Verify that the link is accessible in a private browser window.

If you encounter any difficulties or have questions, please don't hesitate to reach out to our team via our Slack at `#cohort-3-help`. Our Technical Facilitators and Learning Support staff are here to help you navigate any challenges.